hw_05.05.2024 _SQLight/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from quotes import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path('author_create/', views.author_create, name='author_create'),
    path('quotes/<int:author_id>/', views.author_page, name='author_page'),
    path('quote_page/<int:tag_id>/', views.quote_page, name='quote_page'),
    path("<int:page>", views.main, name="root_paginate"),
]

hw_05.05.2024 _SQLight/hw_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path('author_create/', views.author_create, name='author_create'),
    path('quotes/<int:author_id>/', views.author_page, name='author_page'),
    path('quote_page/<int:tag_id>/', views.quote_page, name='quote_page'),
    path('author/delete/', views.author_confirm_delete, name='author_confirm_delete'),
]

hw_05.05.2024 _SQLight/hw_project/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

hw_05.05.2024 _SQLight/hw_project/quotes/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

hw_05.05.2024 _SQLight/hw_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from .models import Author, Quote, Tag



def main(request, page=1):
    # page_number = request.GET.get('page', 1)
    quotes = Quote.objects.all().order_by('-created_at')  # Отримання всіх цитат із бази даних SQLite
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


def author_create(request):
    if request.method == 'POST':
        # Обробка POST-запиту
        fullname = request.POST.get('fullname', '')
        born_date = request.POST.get('born_date', '')
        born_location = request.POST.get('born_location', '')
        description = request.POST.get('description', '')
        quote_text = request.POST.get('quote', '')

        author = Author.objects.filter(fullname=fullname).first()

        if not author:
            author = Author.objects.create(
                fullname=fullname,
                born_date=born_date,
                born_location=born_location,
                description=description
            )

        Quote.objects.create(
            quote=quote_text,
            author=author
        )

        # Після успішного створення автора та цитати перенаправити куди-небудь
        return redirect('quotes:root')

    else:
        # Обробка GET-запиту (відображення форми для створення автора та цитати)
        return render(request, 'author/author_create.html')




def author_confirm_delete(request):
    if request.method == 'POST':
        full_name = request.POST.get('fullname', '')
        try:
            author = get_object_or_404(Author, fullname=full_name)
        except Author.DoesNotExist:
            return render(request, 'author_confirm_delete.html',
                          {'error': f"No Author matches the fullname '{full_name}'"})

        quotes = Quote.objects.filter(author=author)
        quotes.delete()
        author.delete()

        return redirect('quotes:root')

    return render(request, 'author_confirm_delete.html')


def author_page(request, author_id):
    # Отримати об'єкт автора за його ідентифікатором
    author = Author.objects.get(id=author_id)
    return render(request, 'author/author_page.html', {'author': author})


def quote_page(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    quotes = Quote.objects.filter(tags=tag)
    author = Author.objects.filter(quote__tags=tag).first()
    paginator = Paginator(quotes, 10)  # Показує 10 цитат на сторінці
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'author/quote_page.html', {'tag': tag, 'quotes': quotes, 'author': author, 'page_obj': page_obj})

hw_05.05.2024 _SQLight/hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Document</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="http://127.0.0.1:8000/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:logout' %}" class="btn btn-link">Logout</a>
                    <a href="{% url 'author_create' %}" class="btn btn-primary">Add Author</a>
                {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}
            </p>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

hw_05.05.2024 _SQLight/hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">
                {{ quote.author.fullname }}

            </small>
            <a href="{% url 'quotes:author_page' quote.author.id %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:quote_page' tag.id %}">{{ tag }}</a>
                {% endfor %}
            </div>

        </div>
        {% endfor %}
        <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>
        </ul>
        </nav>
    </div>
</div>
{% endblock %}